- name: disabling node js
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable node js:20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install node js and mysql
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
  - nodejs
  - mysql

- name: add user
  ansible.builtin.user:
    name: expense

- name: run app prereqisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: install dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: copy backend service
  ansible.builtin.template:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: install python and mysql dependencies
  ansible.builtin.pip:
    name:
    - PyMySQL
    - cryptography
    executable: pip3.9

- name: import data into mysql
  community.mysql.mysql_db:
    login_user: "{{login_user}}"
    login_password: "{{login_password}}"
    login_host: "{{login_host}}"
    target: /app/schema/backend.sql
    state: import
    name: all

- name: daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable backend
  ansible.builtin.service:
    name: backend
    state: started
  enabled: yes