- name: delete app directory
  ansible.builtin.file:
    path:  "{{ app_location }}"
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory

- name: download and extract code
  ansible.builtin.unarchive:
    src:  "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ compon }}-v2.zip"
    dest: "{{ app_ loaction }}"
    remote_src: yes 